project:
  type: website

website:
  title: "Blog_AlvaroR"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: minty
    css: styles.css

editor: visual

comments:
  giscus:
    repo: Aromanor/Blog_AlvaroR

